export const RACES = {
    Common: [
        "Dragonborn",
        "Dwarf",
        "Elf",
        "Gnome",
        "Half-Elf",
        "Half-Orc",
        "Halfling",
        "Human",
        "Tiefling",
    ],
    Exotic: [
        "Aarakocra",
        "Aasimar",
        "Changeling",
        "Deep Gnome",
        "Duergar",
        "Eladrin",
        "Fairy",
        "Firbolg",
        "Genasi (Air)",
        "Genasi (Earth)",
        "Genasi (Fire)",
        "Genasi (Water)",
        "Githyanki",
        "Githzerai",
        "Goliath",
        "Harengon",
        "Kenku",
        "Locathah",
        "Owlin",
        "Satyr",
        "Sea Elf",
        "Shadar-Kai",
        "Tabaxi",
        "Tortle",
        "Triton",
        "Verdan",
    ],
    Monstrous: [
        "Bugbear",
        "Centaur",
        "Goblin",
        "Grung",
        "Hobgoblin",
        "Kobold",
        "Lizardfolk",
        "Minotaur",
        "Orc",
        "Shifter",
        "Yuan-Ti",
    ],
    "Setting-Specific": [
        "Dragonlance",
        "Eberron",
        "Plane Shift",
        "Ravenloft",
        "Ravnica",
        "Spelljammer",
        "Theros",
    ],
} as const;
