export const RACES = [
    "Aarakocra",
    "Aasimar",
    "Bugbear",
    "Centaur",
    "Changeling",
    "Deep Gnome",
    "Dragonlance",
    "Duergar",
    "Dwarf",
    "Eberron",
    "Eladrin",
    "Elf",
    "Fairy",
    "Firbolg",
    "Genasi (Air)",
    "Genasi (Earth)",
    "Genasi (Fire)",
    "Genasi (Water)",
    "Githyanki",
    "Githzerai",
    "Gnome",
    "Goblin",
    "Goliath",
    "Grung",
    "Half-Elf",
    "Half-Orc",
    "Halfling",
    "Harengon",
    "Hobgoblin",
    "Human",
    "Kenku",
    "Kobold",
    "Lizardfolk",
    "Locathah",
    "Minotaur",
    "Orc",
    "Owlin",
    "Plane Shift",
    "Ravenloft",
    "Ravnica",
    "Satyr",
    "Sea Elf",
    "Shadar-Kai",
    "Shifter",
    "Spelljammer",
    "Tabaxi",
    "Theros",
    "Tiefling",
    "Tortle",
    "Triton",
    "Verdan",
    "Yuan-Ti",
    "Dragonborn",
] as const;
